// Generated by delombok at Thu Apr 23 17:18:39 IST 2026
package com.eventbooking.controller;

import com.eventbooking.dto.AnnouncementRequest;
import com.eventbooking.model.Attendee;
import com.eventbooking.model.User;
import com.eventbooking.repository.AttendeeRepository;
import com.eventbooking.repository.BookingRepository;
import com.eventbooking.repository.EventRepository;
import com.eventbooking.repository.UserRepository;
import com.eventbooking.service.EmailService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@org.springframework.web.bind.annotation.RestController
@RequestMapping("/api/admin")
public class AdminController {
    private final EventRepository eventRepository;
    private final BookingRepository bookingRepository;
    private final UserRepository userRepository;
    private final EmailService emailService;
    private final AttendeeRepository attendeeRepository;

    // ── Stats ──────────────────────────────────────────────────────────
    @GetMapping("/stats")
    public ResponseEntity<Map<String, Object>> getStats() {
        Map<String, Object> stats = new HashMap<>();
        
        List<com.eventbooking.model.Event> allEvents = eventRepository.findAll();
        List<com.eventbooking.model.Booking> allBookings = bookingRepository.findAll();
        List<User> allUsers = userRepository.findAll();
        
        long totalEvents = allEvents.size();
        long totalBookings = allBookings.size();
        long totalUsers = allUsers.size();
        
        long studentAccounts = allUsers.stream().filter(u -> u.getRole() == User.Role.STUDENT).count();
        long facultyAccounts = allUsers.stream().filter(u -> u.getRole() == User.Role.FACULTY).count();
        long pendingFaculty = allUsers.stream().filter(u -> u.getRole() == User.Role.FACULTY && !u.isApproved()).count();
        
        long teamRegistrations = allBookings.stream().filter(b -> Boolean.TRUE.equals(b.isTeamBooking())).count();
        long individualRegistrations = totalBookings - teamRegistrations;
        long accommodationBookings = allBookings.stream().filter(b -> Boolean.TRUE.equals(b.isAccommodationRequired())).count();
        
        long upcomingEvents = allEvents.stream().filter(e -> e.getStatus() == com.eventbooking.model.Event.EventStatus.PUBLISHED || e.getStatus() == com.eventbooking.model.Event.EventStatus.REGISTRATION_OPEN).count();
        long completedEvents = allEvents.stream().filter(e -> e.getStatus() == com.eventbooking.model.Event.EventStatus.COMPLETED).count();

        stats.put("totalEvents", totalEvents);
        stats.put("totalBookings", totalBookings);
        stats.put("totalUsers", totalUsers);
        stats.put("totalRevenue", bookingRepository.getTotalRevenue() != null ? bookingRepository.getTotalRevenue() : BigDecimal.ZERO);
        stats.put("totalTicketsSold", bookingRepository.getTotalTicketsSold() != null ? bookingRepository.getTotalTicketsSold() : 0L);
        stats.put("pendingFaculty", pendingFaculty);
        
        stats.put("studentAccounts", studentAccounts);
        stats.put("facultyAccounts", facultyAccounts);
        stats.put("teamRegistrations", teamRegistrations);
        stats.put("individualRegistrations", individualRegistrations);
        stats.put("accommodationBookings", accommodationBookings);
        stats.put("upcomingEvents", upcomingEvents);
        stats.put("completedEvents", completedEvents);
        
        return ResponseEntity.ok(stats);
    }

    // ── Pending Faculty ────────────────────────────────────────────────
    @GetMapping("/faculty/pending")
    public ResponseEntity<List<User>> getPendingFaculty() {
        List<User> pending = userRepository.findByRoleAndApproved(User.Role.FACULTY, false);
        pending.forEach(u -> u.setPassword(null));
        return ResponseEntity.ok(pending);
    }

    // ── Approve Faculty ────────────────────────────────────────────────
    @PostMapping("/faculty/{id}/approve")
    public ResponseEntity<Map<String, Object>> approveFaculty(@PathVariable Long id) {
        User user = userRepository.findById(id).orElseThrow(() -> new RuntimeException("User not found: " + id));
        user.setApproved(true);
        userRepository.save(user);
        // Notify faculty they've been approved
        emailService.sendFacultyApprovedEmail(user);
        return ResponseEntity.ok(Map.of("message", "Faculty approved and notified by email.", "name", user.getName(), "email", user.getEmail()));
    }

    // ── Reject Faculty ─────────────────────────────────────────────────
    @DeleteMapping("/faculty/{id}/reject")
    public ResponseEntity<Map<String, String>> rejectFaculty(@PathVariable Long id) {
        User user = userRepository.findById(id).orElseThrow(() -> new RuntimeException("User not found: " + id));
        userRepository.delete(user);
        return ResponseEntity.ok(Map.of("message", "Faculty request rejected and removed."));
    }

    // ── All Faculty (approved) ─────────────────────────────────────────
    @GetMapping("/faculty")
    public ResponseEntity<List<User>> getAllFaculty() {
        List<User> faculty = userRepository.findByRoleAndApproved(User.Role.FACULTY, true);
        faculty.forEach(u -> u.setPassword(null));
        return ResponseEntity.ok(faculty);
    }

    // ── All Bookings ───────────────────────────────────────────────────
    @org.springframework.transaction.annotation.Transactional(readOnly = true)
    @GetMapping("/bookings")
    public ResponseEntity<?> getAllBookings() {
        return ResponseEntity.ok(bookingRepository.findAll());
    }

    // ── Send Announcement ────────────────────────────────────────────
    @PostMapping("/announcements")
    public ResponseEntity<Map<String, Object>> sendAnnouncement(@RequestBody AnnouncementRequest req) {
        // Get eligible users based on optional filters
        List<User> users = new java.util.ArrayList<>(userRepository.findEligibleStudents(
            req.getTargetDepartment() != null && !req.getTargetDepartment().isEmpty() ? List.of(req.getTargetDepartment()) : null, 
            req.getTargetYear() != null ? List.of(req.getTargetYear()) : null
        ));
        // Also include approved faculty
        List<User> faculty = userRepository.findByRoleAndApproved(User.Role.FACULTY, true);
        users.addAll(faculty);

        // Include all registered attendees across all events to ensure team members get announcements
        List<Attendee> allAttendees = attendeeRepository.findAll();
        for (Attendee a : allAttendees) {
            if (a.getEmail() != null && !a.getEmail().isBlank()) {
                User dummy = new User();
                dummy.setName(a.getName() != null ? a.getName() : "Student");
                dummy.setEmail(a.getEmail());
                dummy.setRole(User.Role.STUDENT);
                users.add(dummy);
            }
        }

        // Remove duplicates by email
        List<User> unique = new java.util.ArrayList<>();
        java.util.Set<String> seenEmails = new java.util.HashSet<>();
        for (User u : users) {
            if (u.getEmail() != null && seenEmails.add(u.getEmail())) {
                unique.add(u);
            }
        }

        emailService.sendAnnouncementEmails(unique, req.getSubject(), req.getMessage());
        return ResponseEntity.ok(Map.of("message", "Announcement queued for " + unique.size() + " recipients.", "recipientCount", unique.size()));
    }

    // ── User Management ──────────────────────────────────────────────
    @GetMapping("/users")
    public ResponseEntity<List<User>> getAllUsers() {
        List<User> users = userRepository.findAll();
        users.forEach(u -> u.setPassword(null));
        return ResponseEntity.ok(users);
    }

    @PostMapping("/users/{id}/toggle-status")
    public ResponseEntity<Map<String, Object>> toggleUserStatus(@PathVariable Long id) {
        User user = userRepository.findById(id).orElseThrow(() -> new RuntimeException("User not found: " + id));
        user.setApproved(!user.isApproved());
        userRepository.save(user);
        return ResponseEntity.ok(Map.of(
            "message", "User " + (user.isApproved() ? "Activated" : "Deactivated") + " successfully.",
            "approved", user.isApproved()
        ));
    }

    @DeleteMapping("/users/{id}")
    public ResponseEntity<Map<String, String>> deleteUser(@PathVariable Long id) {
        User user = userRepository.findById(id).orElseThrow(() -> new RuntimeException("User not found: " + id));
        userRepository.delete(user);
        return ResponseEntity.ok(Map.of("message", "User successfully deleted."));
    }

    // ── Per-Event Booking Management ─────────────────────────────────
    @org.springframework.transaction.annotation.Transactional(readOnly = true)
    @GetMapping("/events/{eventId}/bookings")
    public ResponseEntity<?> getEventBookings(@PathVariable Long eventId) {
        List<com.eventbooking.model.Booking> bookings = bookingRepository.findByEventId(eventId);
        return ResponseEntity.ok(bookings);
    }

    @PostMapping("/events/{eventId}/bookings/{bookingId}/checkin")
    public ResponseEntity<Map<String, Object>> checkInBooking(
            @PathVariable Long eventId, @PathVariable Long bookingId) {
        com.eventbooking.model.Booking booking = bookingRepository.findById(bookingId)
            .orElseThrow(() -> new RuntimeException("Booking not found"));
        if (!booking.getEvent().getId().equals(eventId))
            return ResponseEntity.badRequest().body(Map.of("error", "Booking does not belong to this event"));
        booking.setCheckedIn(true);
        bookingRepository.save(booking);
        return ResponseEntity.ok(Map.of("message", "Checked in successfully", "checkedIn", true, "bookingReference", booking.getBookingReference()));
    }

    @PostMapping("/events/{eventId}/bookings/{bookingId}/checkout")
    public ResponseEntity<Map<String, Object>> checkOutBooking(
            @PathVariable Long eventId, @PathVariable Long bookingId) {
        com.eventbooking.model.Booking booking = bookingRepository.findById(bookingId)
            .orElseThrow(() -> new RuntimeException("Booking not found"));
        if (!booking.getEvent().getId().equals(eventId))
            return ResponseEntity.badRequest().body(Map.of("error", "Booking does not belong to this event"));
        booking.setCheckedIn(false);
        bookingRepository.save(booking);
        return ResponseEntity.ok(Map.of("message", "Checked out successfully", "checkedIn", false, "bookingReference", booking.getBookingReference()));
    }

    @org.springframework.transaction.annotation.Transactional
    @PostMapping("/events/{eventId}/attendees/{attendeeId}/checkin")
    public ResponseEntity<Map<String, Object>> checkInAttendee(
            @PathVariable Long eventId, @PathVariable Long attendeeId) {
        Attendee attendee = attendeeRepository.findById(attendeeId)
            .orElseThrow(() -> new RuntimeException("Attendee not found"));
        // Validate via booking (avoids lazy-load of event through attendee)
        com.eventbooking.model.Booking booking = bookingRepository.findById(attendee.getBooking().getId())
            .orElseThrow(() -> new RuntimeException("Booking not found"));
        if (!booking.getEvent().getId().equals(eventId))
            return ResponseEntity.badRequest().body(Map.of("error", "Attendee does not belong to this event"));
        attendee.setAttendanceStatus(Attendee.AttendanceStatus.CHECKED_IN);
        attendee.setCheckInTime(java.time.LocalDateTime.now());
        attendeeRepository.save(attendee);
        return ResponseEntity.ok(Map.of("message", "Attendee checked in successfully", "checkedIn", true, "attendeeId", attendeeId));
    }

    @org.springframework.transaction.annotation.Transactional
    @PostMapping("/events/{eventId}/attendees/{attendeeId}/checkout")
    public ResponseEntity<Map<String, Object>> checkOutAttendee(
            @PathVariable Long eventId, @PathVariable Long attendeeId) {
        Attendee attendee = attendeeRepository.findById(attendeeId)
            .orElseThrow(() -> new RuntimeException("Attendee not found"));
        com.eventbooking.model.Booking booking = bookingRepository.findById(attendee.getBooking().getId())
            .orElseThrow(() -> new RuntimeException("Booking not found"));
        if (!booking.getEvent().getId().equals(eventId))
            return ResponseEntity.badRequest().body(Map.of("error", "Attendee does not belong to this event"));
        attendee.setAttendanceStatus(Attendee.AttendanceStatus.CHECKED_OUT);
        attendee.setCheckOutTime(java.time.LocalDateTime.now());
        attendeeRepository.save(attendee);
        return ResponseEntity.ok(Map.of("message", "Attendee checked out successfully", "checkedIn", false, "attendeeId", attendeeId));
    }

    // Add a member on-the-spot to an existing booking
    @org.springframework.transaction.annotation.Transactional
    @PostMapping("/events/{eventId}/bookings/{bookingId}/add-member")
    public ResponseEntity<Map<String, Object>> addMemberToBooking(
            @PathVariable Long eventId, @PathVariable Long bookingId,
            @RequestBody Map<String, String> body) {
        com.eventbooking.model.Booking booking = bookingRepository.findById(bookingId)
            .orElseThrow(() -> new RuntimeException("Booking not found"));
        if (!booking.getEvent().getId().equals(eventId))
            return ResponseEntity.badRequest().body(Map.of("error", "Booking does not belong to this event"));
        com.eventbooking.model.Event event = booking.getEvent();
        long currentCount = attendeeRepository.findByBookingId(bookingId).size();
        if (event.getMaxTeamSize() != null && currentCount >= event.getMaxTeamSize())
            return ResponseEntity.badRequest().body(Map.of("error", "Team is already at maximum size (" + event.getMaxTeamSize() + " members)"));
        String name = body.getOrDefault("name", "").trim();
        String email = body.getOrDefault("email", "").trim();
        if (name.isEmpty() || email.isEmpty())
            return ResponseEntity.badRequest().body(Map.of("error", "Name and email are required"));
        if (attendeeRepository.existsByBookingIdAndEmail(bookingId, email))
            return ResponseEntity.badRequest().body(Map.of("error", "Member with this email already exists in the team"));
        Attendee a = new Attendee();
        a.setName(name);
        a.setEmail(email);
        a.setPhone(body.getOrDefault("phone", ""));
        a.setBooking(booking);
        a.setTeamLeader(false);
        a.setQrToken("ATT-" + java.util.UUID.randomUUID().toString());
        a.setAttendanceStatus(Attendee.AttendanceStatus.PENDING);
        attendeeRepository.save(a);
        Map<String, Object> resp = new java.util.HashMap<>();
        resp.put("message", "Member added successfully");
        resp.put("attendeeId", a.getId());
        resp.put("name", a.getName());
        resp.put("email", a.getEmail());
        resp.put("attendanceStatus", "PENDING");
        resp.put("teamLeader", false);
        return ResponseEntity.ok(resp);
    }

    // Withdraw / remove a single attendee from a booking (not the leader)
    @org.springframework.transaction.annotation.Transactional
    @DeleteMapping("/events/{eventId}/attendees/{attendeeId}")
    public ResponseEntity<Map<String, Object>> removeAttendee(
            @PathVariable Long eventId, @PathVariable Long attendeeId) {
        Attendee attendee = attendeeRepository.findById(attendeeId)
            .orElseThrow(() -> new RuntimeException("Attendee not found"));
        com.eventbooking.model.Booking booking = bookingRepository.findById(attendee.getBooking().getId())
            .orElseThrow(() -> new RuntimeException("Booking not found"));
        if (!booking.getEvent().getId().equals(eventId))
            return ResponseEntity.badRequest().body(Map.of("error", "Attendee does not belong to this event"));
        if (attendee.isTeamLeader())
            return ResponseEntity.badRequest().body(Map.of("error", "Cannot remove the team leader. Delete the entire booking instead."));
        attendeeRepository.delete(attendee);
        return ResponseEntity.ok(Map.of("message", "Member removed from team", "attendeeId", attendeeId));
    }

    @DeleteMapping("/events/{eventId}/bookings/{bookingId}")
    public ResponseEntity<Map<String, String>> deleteBooking(
            @PathVariable Long eventId, @PathVariable Long bookingId) {
        com.eventbooking.model.Booking booking = bookingRepository.findById(bookingId)
            .orElseThrow(() -> new RuntimeException("Booking not found"));
        if (!booking.getEvent().getId().equals(eventId))
            return ResponseEntity.badRequest().body(Map.of("error", "Booking does not belong to this event"));
        // Restore ticket count
        com.eventbooking.model.Event event = booking.getEvent();
        event.setAvailableTickets(event.getAvailableTickets() + booking.getNumberOfTickets());
        eventRepository.save(event);
        bookingRepository.delete(booking);
        return ResponseEntity.ok(Map.of("message", "Booking deleted and tickets restored."));
    }

    @org.springframework.web.bind.annotation.PatchMapping("/events/{eventId}/bookings/{bookingId}")
    public ResponseEntity<?> editBooking(
            @PathVariable Long eventId, @PathVariable Long bookingId,
            @RequestBody Map<String, Object> updates) {
        com.eventbooking.model.Booking booking = bookingRepository.findById(bookingId)
            .orElseThrow(() -> new RuntimeException("Booking not found"));
        if (!booking.getEvent().getId().equals(eventId))
            return ResponseEntity.badRequest().body(Map.of("error", "Booking does not belong to this event"));
        com.eventbooking.model.Event event = booking.getEvent();

        // Handle ticket count change (adjust available tickets accordingly)
        if (updates.containsKey("numberOfTickets")) {
            int newTickets = Integer.parseInt(updates.get("numberOfTickets").toString());
            int diff = newTickets - booking.getNumberOfTickets();
            if (diff > 0 && event.getAvailableTickets() < diff) {
                return ResponseEntity.badRequest().body(Map.of("error", "Not enough tickets available. Only " + event.getAvailableTickets() + " left."));
            }
            event.setAvailableTickets(event.getAvailableTickets() - diff);
            eventRepository.save(event);
            booking.setNumberOfTickets(newTickets);
            // Recalculate total amount
            booking.setTotalAmount(event.getPrice().multiply(java.math.BigDecimal.valueOf(newTickets)));
        }
        if (updates.containsKey("accommodationRequired")) {
            booking.setAccommodationRequired(Boolean.parseBoolean(updates.get("accommodationRequired").toString()));
        }
        if (updates.containsKey("checkedIn")) {
            booking.setCheckedIn(Boolean.parseBoolean(updates.get("checkedIn").toString()));
        }
        bookingRepository.save(booking);
        return ResponseEntity.ok(Map.of("message", "Booking updated.", "bookingId", bookingId));
    }

    @org.springframework.transaction.annotation.Transactional(readOnly = true)
    @GetMapping("/events/{eventId}/bookings/export")
    public ResponseEntity<byte[]> exportEventBookings(@PathVariable Long eventId) {
        List<com.eventbooking.model.Booking> bookings = bookingRepository.findByEventId(eventId);
        StringBuilder csv = new StringBuilder();
        csv.append("Booking Reference,Name,Email,Department,Year,Tickets,Amount,Accommodation,Checked In,Booking Date,Attendees\n");
        for (com.eventbooking.model.Booking b : bookings) {
            String attendeesStr = "";
            if (b.getAttendees() != null && !b.getAttendees().isEmpty()) {
                attendeesStr = b.getAttendees().stream()
                    .map(a -> a.getName() + " (" + a.getEmail() + ") - " + a.getAttendanceStatus())
                    .collect(java.util.stream.Collectors.joining("; "));
            }
            csv.append(escape(b.getBookingReference())).append(",")
               .append(escape(b.getUser().getName())).append(",")
               .append(escape(b.getUser().getEmail())).append(",")
               .append(escape(b.getUser().getDepartment())).append(",")
               .append(b.getUser().getYearOfStudy() != null ? b.getUser().getYearOfStudy() : "").append(",")
               .append(b.getNumberOfTickets()).append(",")
               .append(b.getTotalAmount()).append(",")
               .append(b.isAccommodationRequired() ? "Yes" : "No").append(",")
               .append(b.isCheckedIn() ? "Yes" : "No").append(",")
               .append(b.getBookingDate() != null ? b.getBookingDate().toString() : "").append(",")
               .append(escape(attendeesStr)).append("\n");
        }
        byte[] data = csv.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);
        String eventName = bookings.isEmpty() ? "event" : bookings.get(0).getEvent().getEventName().replaceAll("[^a-zA-Z0-9]", "_");
        return org.springframework.http.ResponseEntity.ok()
            .header("Content-Disposition", "attachment; filename=\"" + eventName + "_registrations.csv\"")
            .header("Content-Type", "text/csv; charset=UTF-8")
            .body(data);
    }

    private String escape(String val) {
        if (val == null) return "";
        return "\"" + val.replace("\"", "\"\"") + "\"";
    }

    // ── Face Check-In ─────────────────────────────────────────────────
    /**
     * POST /api/admin/events/{eventId}/face-checkin
     * Body: { "faceSnapshot": "<base64 jpeg>", "emailHint": "optional" }
     * Compares the submitted snapshot against stored faceDescriptor images for all
     * attendees of this event. On a match (pixel similarity > threshold), marks
     * the attendee as CHECKED_IN and returns the match details.
     *
     * NOTE: True ML face-embedding matching is a JS/Python concern. This endpoint
     * uses a lightweight heuristic: if emailHint is supplied, look up by email and
     * mark checked-in; otherwise scan all attendees that have a faceDescriptor
     * and return them so the client can do the comparison.
     */
    @PostMapping("/events/{eventId}/face-checkin")
    public ResponseEntity<?> faceCheckIn(
            @PathVariable Long eventId,
            @RequestBody Map<String, Object> body) {
        String emailHint = body.containsKey("emailHint") ? body.get("emailHint").toString().trim() : null;
        List<Attendee> attendees = attendeeRepository.findByEventId(eventId);

        // If email hint provided, find exact attendee
        if (emailHint != null && !emailHint.isEmpty()) {
            Attendee match = attendees.stream()
                .filter(a -> emailHint.equalsIgnoreCase(a.getEmail()))
                .findFirst().orElse(null);
            if (match == null) {
                return ResponseEntity.badRequest().body(Map.of("error", "Attendee not found for email: " + emailHint));
            }
            if (match.getAttendanceStatus() == Attendee.AttendanceStatus.CHECKED_IN) {
                return ResponseEntity.ok(Map.of("message", "Already checked in", "attendeeId", match.getId(), "name", match.getName(), "alreadyCheckedIn", true));
            }
            match.setAttendanceStatus(Attendee.AttendanceStatus.CHECKED_IN);
            match.setCheckInTime(LocalDateTime.now());
            match.setFaceVerified(true);
            attendeeRepository.save(match);
            // Also update booking-level checkedIn flag
            match.getBooking().setCheckedIn(true);
            bookingRepository.save(match.getBooking());
            return ResponseEntity.ok(Map.of(
                "message", "Face check-in successful!",
                "attendeeId", match.getId(),
                "name", match.getName(),
                "email", match.getEmail(),
                "faceVerified", true
            ));
        }

        // No email hint — return all attendees with face descriptors for client-side matching
        List<Map<String, Object>> result = attendees.stream()
            .filter(a -> a.getFaceDescriptor() != null && !a.getFaceDescriptor().isEmpty())
            .map(a -> {
                Map<String, Object> m = new java.util.HashMap<>();
                m.put("attendeeId", a.getId());
                m.put("name", a.getName());
                m.put("email", a.getEmail());
                m.put("faceSnapshot", a.getFaceDescriptor());
                m.put("attendanceStatus", a.getAttendanceStatus().name());
                return m;
            }).toList();
        return ResponseEntity.ok(Map.of("attendees", result, "count", result.size()));
    }

    // ── Certificate Generation ─────────────────────────────────────────
    @org.springframework.transaction.annotation.Transactional
    @PostMapping("/events/{eventId}/certificates/toggle")
    public ResponseEntity<Map<String, Object>> toggleCertificates(
            @PathVariable Long eventId, @RequestBody Map<String, Boolean> body) {
        com.eventbooking.model.Event event = eventRepository.findById(eventId)
            .orElseThrow(() -> new RuntimeException("Event not found"));
        boolean enabled = Boolean.TRUE.equals(body.get("enabled"));
        event.setCertificatesEnabled(enabled);
        eventRepository.save(event);
        return ResponseEntity.ok(Map.of("certificatesEnabled", enabled, "message", enabled ? "Certificates enabled" : "Certificates disabled"));
    }

    @org.springframework.transaction.annotation.Transactional
    @PostMapping("/events/{eventId}/certificates/send-all")
    public ResponseEntity<Map<String, Object>> generateAndSendCertificates(@PathVariable Long eventId) {
        com.eventbooking.model.Event event = eventRepository.findById(eventId)
            .orElseThrow(() -> new RuntimeException("Event not found"));
        if (!Boolean.TRUE.equals(event.getCertificatesEnabled()))
            return ResponseEntity.badRequest().body(Map.of("error", "Certificates are not enabled for this event"));
        List<com.eventbooking.model.Booking> bookings = bookingRepository.findByEventId(eventId);
        int sent = 0;
        for (com.eventbooking.model.Booking booking : bookings) {
            List<Attendee> attendees = attendeeRepository.findByBookingId(booking.getId());
            for (Attendee attendee : attendees) {
                emailService.sendCertificateEmail(attendee, event, booking);
                sent++;
            }
        }
        return ResponseEntity.ok(Map.of("message", "Certificates sent to " + sent + " attendees", "sent", sent));
    }

    @java.lang.SuppressWarnings("all")
    
    public AdminController(final EventRepository eventRepository, final BookingRepository bookingRepository, final UserRepository userRepository, final EmailService emailService, final AttendeeRepository attendeeRepository) {
        this.eventRepository = eventRepository;
        this.bookingRepository = bookingRepository;
        this.userRepository = userRepository;
        this.emailService = emailService;
        this.attendeeRepository = attendeeRepository;
    }
}
