// Generated by delombok at Thu Apr 23 17:18:39 IST 2026
package com.eventbooking.controller;

import com.eventbooking.dto.AuthResponse;
import com.eventbooking.dto.LoginRequest;
import com.eventbooking.dto.RegisterRequest;
import com.eventbooking.service.AuthService;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/auth")
public class AuthController {
    private final AuthService authService;
    private final com.eventbooking.service.EmailService emailService;
    
    private final java.util.Map<String, String> otpStore = new java.util.concurrent.ConcurrentHashMap<>();
    private final java.util.Map<String, Boolean> verifiedEmails = new java.util.concurrent.ConcurrentHashMap<>();

    @PostMapping("/send-otp")
    public ResponseEntity<java.util.Map<String, String>> sendOtp(@RequestBody java.util.Map<String, String> body) {
        String email = body.get("email");
        if (email == null || email.isBlank()) {
            return ResponseEntity.badRequest().body(java.util.Map.of("error", "Email is required"));
        }
        String otp = String.format("%06d", new java.util.Random().nextInt(999999));
        otpStore.put(email, otp);
        emailService.sendSimpleEmail(email, "EventSphere OTP Verification", "Your OTP for EventSphere registration is: " + otp + "\n\nPlease do not share this with anyone.");
        return ResponseEntity.ok(java.util.Map.of("message", "OTP sent successfully"));
    }

    @PostMapping("/verify-otp")
    public ResponseEntity<java.util.Map<String, String>> verifyOtp(@RequestBody java.util.Map<String, String> body) {
        String email = body.get("email");
        String otp = body.get("otp");
        if (email == null || otp == null) {
            return ResponseEntity.badRequest().body(java.util.Map.of("error", "Email and OTP are required"));
        }
        String storedOtp = otpStore.get(email);
        if (storedOtp != null && storedOtp.equals(otp)) {
            otpStore.remove(email);
            verifiedEmails.put(email, true);
            return ResponseEntity.ok(java.util.Map.of("message", "Email verified successfully"));
        }
        return ResponseEntity.status(400).body(java.util.Map.of("error", "Invalid or expired OTP"));
    }

    @PostMapping("/register")
    public ResponseEntity<AuthResponse> register(@Valid @RequestBody RegisterRequest request) {
        if (!Boolean.TRUE.equals(verifiedEmails.get(request.getEmail()))) {
            throw new RuntimeException("Email is not verified. Please verify your email with OTP first.");
        }
        AuthResponse response = authService.register(request);
        verifiedEmails.remove(request.getEmail());
        return ResponseEntity.ok(response);
    }

    @PostMapping("/login")
    public ResponseEntity<AuthResponse> login(@Valid @RequestBody LoginRequest request) {
        AuthResponse response = authService.login(request);
        return ResponseEntity.ok(response);
    }

    // ── Login with OTP (optional passwordless) ──────────────────────
    @PostMapping("/login-otp")
    public ResponseEntity<java.util.Map<String, String>> loginOtpSend(@RequestBody java.util.Map<String, String> body) {
        String email = body.get("email");
        if (email == null || email.isBlank())
            return ResponseEntity.badRequest().body(java.util.Map.of("error", "Email is required"));
        // Check if user exists
        if (!authService.userExistsByEmail(email))
            return ResponseEntity.badRequest().body(java.util.Map.of("error", "No account found with this email"));
        String otp = String.format("%06d", new java.util.Random().nextInt(999999));
        otpStore.put("login_" + email, otp);
        emailService.sendSimpleEmail(email, "EventSphere Login OTP",
            "Your OTP for EventSphere login is: " + otp + "\n\nThis OTP is valid for 5 minutes.\nPlease do not share this with anyone.");
        return ResponseEntity.ok(java.util.Map.of("message", "Login OTP sent to " + email));
    }

    @PostMapping("/login-otp-verify")
    public ResponseEntity<?> loginOtpVerify(@RequestBody java.util.Map<String, String> body) {
        String email = body.get("email");
        String otp = body.get("otp");
        if (email == null || otp == null)
            return ResponseEntity.badRequest().body(java.util.Map.of("error", "Email and OTP are required"));
        String stored = otpStore.get("login_" + email);
        if (stored != null && stored.equals(otp)) {
            otpStore.remove("login_" + email);
            AuthResponse response = authService.loginByEmail(email);
            return ResponseEntity.ok(response);
        }
        return ResponseEntity.status(400).body(java.util.Map.of("error", "Invalid or expired OTP"));
    }

    @java.lang.SuppressWarnings("all")
    
    public AuthController(final AuthService authService, final com.eventbooking.service.EmailService emailService) {
        this.authService = authService;
        this.emailService = emailService;
    }
}
