// Generated by delombok at Thu Apr 23 17:18:39 IST 2026
package com.eventbooking.controller;

import com.eventbooking.dto.BookingRequest;
import com.eventbooking.model.Booking;
import com.eventbooking.service.BookingService;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/bookings")
public class BookingController {
    private final BookingService bookingService;
    private final com.eventbooking.service.EmailService emailService;

    @PostMapping
    public ResponseEntity<?> createBooking(@Valid @RequestBody BookingRequest request, Authentication authentication) {
        try {
            String userEmail = authentication.getName();
            Booking booking = bookingService.createBooking(request, userEmail);
            return ResponseEntity.status(HttpStatus.CREATED).body(booking);
        } catch (RuntimeException e) {
            return ResponseEntity.badRequest().body(Map.of("error", e.getMessage()));
        }
    }

    @GetMapping("/user/{userId}")
    public ResponseEntity<List<Booking>> getBookingsByUser(@PathVariable Long userId) {
        return ResponseEntity.ok(bookingService.getBookingsByUser(userId));
    }

    @GetMapping("/{id}")
    public ResponseEntity<Booking> getBookingById(@PathVariable Long id) {
        return ResponseEntity.ok(bookingService.getBookingById(id));
    }

    @GetMapping
    public ResponseEntity<List<Booking>> getAllBookings() {
        return ResponseEntity.ok(bookingService.getAllBookings());
    }

    @DeleteMapping("/{id}/cancel")
    public ResponseEntity<?> cancelBooking(@PathVariable Long id, Authentication authentication) {
        try {
            String userEmail = authentication.getName();
            Booking cancelled = bookingService.cancelBooking(id, userEmail);
            return ResponseEntity.ok(Map.of(
                "message", "Registration cancelled successfully.",
                "bookingReference", cancelled.getBookingReference()
            ));
        } catch (RuntimeException e) {
            return ResponseEntity.badRequest().body(Map.of("error", e.getMessage()));
        }
    }

    // ── Certificate Download ────────────────────────────────────────────
    @GetMapping("/{bookingId}/attendees/{attendeeId}/certificate")
    public ResponseEntity<?> downloadCertificate(
            @PathVariable Long bookingId, @PathVariable Long attendeeId) {
        Booking booking = bookingService.getBookingById(bookingId);
        if (booking == null || booking.getEvent() == null)
            return ResponseEntity.notFound().build();
        if (!Boolean.TRUE.equals(booking.getEvent().getCertificatesEnabled()))
            return ResponseEntity.badRequest().body(Map.of("error", "Certificates are not enabled for this event"));
        var attendee = booking.getAttendees().stream()
            .filter(a -> a.getId().equals(attendeeId)).findFirst()
            .orElse(null);
        if (attendee == null)
            return ResponseEntity.notFound().build();
        String html = emailService.buildCertificateHtml(attendee, booking.getEvent(), booking);
        return ResponseEntity.ok()
            .header("Content-Type", "text/html; charset=UTF-8")
            .body(html);
    }

    @java.lang.SuppressWarnings("all")
    
    public BookingController(final BookingService bookingService, final com.eventbooking.service.EmailService emailService) {
        this.bookingService = bookingService;
        this.emailService = emailService;
    }
}
