// Generated by delombok at Thu Apr 23 17:18:39 IST 2026
package com.eventbooking.controller;

import com.eventbooking.dto.CampaignRequest;
import com.eventbooking.model.Event;
import com.eventbooking.repository.EventRepository;
import com.eventbooking.service.EventService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/events")
public class EventController {
    private final EventRepository eventRepository;
    private final EventService eventService;

    /**
     * GET /api/events
     * Public endpoint — returns student-visible events.
     * Visible statuses: PUBLISHED, REGISTRATION_OPEN, REGISTRATION_PAUSED, REGISTRATION_CLOSED
     */
    @GetMapping
    public ResponseEntity<List<Event>> getAll(@RequestParam(required = false) String search, @RequestParam(required = false) String department) {
        var visibleStatuses = java.util.List.of(Event.EventStatus.PUBLISHED, Event.EventStatus.REGISTRATION_OPEN, Event.EventStatus.REGISTRATION_PAUSED, Event.EventStatus.REGISTRATION_CLOSED);
        List<Event> events;
        if (search != null && !search.isBlank()) {
            events = eventRepository.findVisibleBySearch(visibleStatuses, search.trim());
        } else if (department != null && !department.isBlank() && !department.equalsIgnoreCase("All")) {
            events = eventRepository.findVisibleByDepartment(visibleStatuses, department.trim());
        } else {
            events = eventRepository.findByStatusIn(visibleStatuses);
        }
        return ResponseEntity.ok(events);
    }

    /**
     * GET /api/events/all
     * Admin/Faculty endpoint — returns ALL events including CANCELLED.
     */
    @GetMapping("/all")
    public ResponseEntity<List<Event>> getAllIncludingCancelled(java.security.Principal principal) {
        if (principal == null) return ResponseEntity.status(401).build();
        com.eventbooking.model.User user = eventService.getUserByEmail(principal.getName());
        if (user.getRole() == com.eventbooking.model.User.Role.ADMIN) {
            return ResponseEntity.ok(eventRepository.findAll());
        }
        List<Event> allEvents = eventRepository.findAll();
        List<Event> myEvents = allEvents.stream().filter(e -> 
            (e.getCreatedBy() != null && e.getCreatedBy().getId().equals(user.getId())) ||
            (e.getCoordinators() != null && e.getCoordinators().stream().anyMatch(c -> c.getId().equals(user.getId())))
        ).toList();
        return ResponseEntity.ok(myEvents);
    }

    @GetMapping("/{id}")
    public ResponseEntity<Event> getById(@PathVariable Long id) {
        return eventRepository.findById(id).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build());
    }

    @PostMapping
    public ResponseEntity<Event> create(@RequestBody Event event, java.security.Principal principal) {
        if (principal == null) return ResponseEntity.status(401).build();
        return ResponseEntity.ok(eventService.createEvent(event, principal.getName()));
    }

    @PutMapping("/{id}")
    public ResponseEntity<Event> update(@PathVariable Long id, @RequestBody Event event) {
        return ResponseEntity.ok(eventService.updateEvent(id, event));
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        eventRepository.deleteById(id);
        return ResponseEntity.noContent().build();
    }

    // ── Cancel event and notify all bookers ──────────────────────────────────
    @PostMapping("/{id}/cancel")
    public ResponseEntity<Map<String, Object>> cancel(@PathVariable Long id) {
        return ResponseEntity.ok(eventService.cancelEvent(id));
    }

    // ── Lifecycle management endpoints ────────────────────────────────────────
    @PostMapping("/{id}/publish")
    public ResponseEntity<?> publish(@PathVariable Long id) {
        try {
            Event e = eventService.publishEvent(id);
            return ResponseEntity.ok(Map.of("message", "Event published", "status", e.getStatus().name(), "eventId", e.getId()));
        } catch (Exception ex) {
            return ResponseEntity.internalServerError().body(Map.of("error", ex.getMessage()));
        }
    }

    @PostMapping("/{id}/open-registration")
    public ResponseEntity<?> openRegistration(@PathVariable Long id) {
        try {
            Event e = eventService.openRegistration(id);
            return ResponseEntity.ok(Map.of("message", "Registration opened", "status", e.getStatus().name(), "eventId", e.getId()));
        } catch (Exception ex) {
            return ResponseEntity.internalServerError().body(Map.of("error", ex.getMessage()));
        }
    }

    @PostMapping("/{id}/pause-registration")
    public ResponseEntity<?> pauseRegistration(@PathVariable Long id) {
        try {
            Event e = eventService.pauseRegistration(id);
            return ResponseEntity.ok(Map.of("message", "Registration paused", "status", e.getStatus().name(), "eventId", e.getId()));
        } catch (Exception ex) {
            return ResponseEntity.internalServerError().body(Map.of("error", ex.getMessage()));
        }
    }

    @PostMapping("/{id}/close-registration")
    public ResponseEntity<?> closeRegistration(@PathVariable Long id) {
        try {
            Event e = eventService.closeRegistration(id);
            return ResponseEntity.ok(Map.of("message", "Registration closed", "status", e.getStatus().name(), "eventId", e.getId()));
        } catch (Exception ex) {
            return ResponseEntity.internalServerError().body(Map.of("error", ex.getMessage()));
        }
    }

    @PostMapping("/{id}/postpone")
    public ResponseEntity<?> postpone(@PathVariable Long id) {
        try {
            Event e = eventService.postponeEvent(id);
            return ResponseEntity.ok(Map.of("message", "Event postponed", "status", e.getStatus().name(), "eventId", e.getId()));
        } catch (Exception ex) {
            return ResponseEntity.internalServerError().body(Map.of("error", ex.getMessage()));
        }
    }

    @PostMapping("/{id}/complete")
    public ResponseEntity<?> complete(@PathVariable Long id) {
        try {
            Event e = eventService.completeEvent(id);
            return ResponseEntity.ok(Map.of("message", "Event completed", "status", e.getStatus().name(), "eventId", e.getId()));
        } catch (Exception ex) {
            return ResponseEntity.internalServerError().body(Map.of("error", ex.getMessage()));
        }
    }

    @PostMapping("/{id}/coordinators/{userId}")
    public ResponseEntity<?> addCoordinator(@PathVariable Long id, @PathVariable Long userId) {
        try {
            eventService.addCoordinator(id, userId);
            return ResponseEntity.ok(Map.of("message", "Coordinator added successfully"));
        } catch (Exception ex) {
            return ResponseEntity.internalServerError().body(Map.of("error", ex.getMessage()));
        }
    }

    @DeleteMapping("/{id}/coordinators/{userId}")
    public ResponseEntity<?> removeCoordinator(@PathVariable Long id, @PathVariable Long userId) {
        try {
            eventService.removeCoordinator(id, userId);
            return ResponseEntity.ok(Map.of("message", "Coordinator removed successfully"));
        } catch (Exception ex) {
            return ResponseEntity.internalServerError().body(Map.of("error", ex.getMessage()));
        }
    }

    // ── Approval Workflow ─────────────────────────────────────────────────────

    /** Faculty: submit DRAFT event for admin approval */
    @PostMapping("/{id}/submit-approval")
    public ResponseEntity<?> submitForApproval(@PathVariable Long id) {
        try {
            Event e = eventService.submitForApproval(id);
            return ResponseEntity.ok(Map.of("message", "Submitted for approval", "status", e.getStatus().name()));
        } catch (Exception ex) {
            return ResponseEntity.badRequest().body(Map.of("error", ex.getMessage()));
        }
    }

    /** Admin: approve event */
    @PostMapping("/{id}/approve")
    public ResponseEntity<?> approve(@PathVariable Long id) {
        try {
            Event e = eventService.approveEvent(id);
            return ResponseEntity.ok(Map.of("message", "Event approved", "status", e.getStatus().name()));
        } catch (Exception ex) {
            return ResponseEntity.badRequest().body(Map.of("error", ex.getMessage()));
        }
    }

    /** Admin: reject event with reason */
    @PostMapping("/{id}/reject")
    public ResponseEntity<?> reject(@PathVariable Long id, @RequestBody Map<String, String> body) {
        try {
            String reason = body.getOrDefault("reason", "No reason provided");
            Event e = eventService.rejectEvent(id, reason);
            return ResponseEntity.ok(Map.of("message", "Event rejected", "status", e.getStatus().name()));
        } catch (Exception ex) {
            return ResponseEntity.badRequest().body(Map.of("error", ex.getMessage()));
        }
    }

    /** Admin: get all events pending approval */
    @GetMapping("/pending-approval")
    public ResponseEntity<List<Event>> getPendingApproval() {
        List<Event> pending = eventRepository.findByStatus(Event.EventStatus.PENDING_APPROVAL);
        return ResponseEntity.ok(pending);
    }

    // ── Send campaign emails to eligible users ────────────────────────────────
    @PostMapping(value = "/{id}/campaign", consumes = {"multipart/form-data"})
    public ResponseEntity<Map<String, Object>> campaign(@PathVariable Long id, @RequestParam(required = false) String customMessage, @RequestParam(required = false) org.springframework.web.multipart.MultipartFile file) {
        try {
            return ResponseEntity.ok(eventService.sendCampaign(id, customMessage, file));
        } catch (Exception ex) {
            return ResponseEntity.internalServerError().body(Map.of("error", ex.getMessage()));
        }
    }

    public EventController(final EventRepository eventRepository, final EventService eventService) {
        this.eventRepository = eventRepository;
        this.eventService = eventService;
    }
}
