// Generated by delombok at Thu Apr 23 17:18:39 IST 2026
package com.eventbooking.controller;

import com.eventbooking.model.Booking;
import com.eventbooking.service.BookingService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.Map;

@RestController
@RequestMapping("/api/qr")
public class QRController {
    private final BookingService bookingService;

    @PostMapping("/validate")
    public ResponseEntity<?> validateQR(@RequestBody Map<String, String> request) {
        String reference = request.get("bookingReference");
        if (reference == null || reference.isBlank()) {
            return ResponseEntity.badRequest().body(Map.of("valid", false, "message", "QR reference is required"));
        }
        // If the QR contains JSON (like the new attendee format), extract the token
        if (reference.trim().startsWith("{")) {
            try {
                com.fasterxml.jackson.databind.ObjectMapper mapper = new com.fasterxml.jackson.databind.ObjectMapper();
                java.util.Map<String, Object> map = mapper.readValue(reference, new com.fasterxml.jackson.core.type.TypeReference<java.util.Map<String, Object>>(){});
                if (map.containsKey("token")) {
                    reference = String.valueOf(map.get("token"));
                }
            } catch (Exception e) {
                // Ignore, let it fall back to alphanumeric strip
            }
        }
        
        // Only strip out bad characters if it's not an ATT- token with dashes
        // The ATT token format is ATT-UUID, which only contains alphanumeric and dash
        reference = reference.replaceAll("[^A-Za-z0-9-]", "").trim();
        try {
            Map<String, Object> resp = bookingService.validateAndCheckIn(reference);
            resp.put("valid", true);
            resp.put("message", "✅ Check-in successful!");
            return ResponseEntity.ok(resp);
        } catch (RuntimeException e) {
            String message = e.getMessage();
            boolean isAlreadyCheckedIn = message != null && message.contains("already been checked in");
            return ResponseEntity.badRequest().body(Map.of("valid", false, "message", isAlreadyCheckedIn ? "⚠️ " + message : "❌ " + message, "alreadyCheckedIn", isAlreadyCheckedIn));
        }
    }



    @java.lang.SuppressWarnings("all")
    
    public QRController(final BookingService bookingService) {
        this.bookingService = bookingService;
    }
}
