// Generated by delombok at Thu Apr 23 17:18:39 IST 2026
package com.eventbooking.controller;

import com.eventbooking.model.User;
import com.eventbooking.repository.UserRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.Map;

@RestController
@RequestMapping("/api/users")
public class UserController {
    private final UserRepository userRepository;

    @java.lang.SuppressWarnings("all")
    
    public UserController(final UserRepository userRepository) {
        this.userRepository = userRepository;
    }
}
