// Generated by delombok at Thu Apr 23 17:18:39 IST 2026
package com.eventbooking.config;

import com.eventbooking.model.User;
import com.eventbooking.repository.UserRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

@Component
public class DataInitializer implements CommandLineRunner {
    @java.lang.SuppressWarnings("all")
    
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(DataInitializer.class);
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    @Override
    public void run(String... args) {
        seedAdmin();
        printStartupInfo();
    }

    private void seedAdmin() {
        String adminEmail = "admin@veltech.edu.in";
        if (!userRepository.existsByEmail(adminEmail)) {
            User admin = new User();
            admin.setName("Admin");
            admin.setEmail(adminEmail);
            admin.setPassword(passwordEncoder.encode("Admin@123"));
            admin.setRole(User.Role.ADMIN);
            admin.setDepartment("Administration");
            admin.setApproved(true);
            userRepository.save(admin);
            log.info("✅ Default ADMIN created → admin@veltech.edu.in / Admin@123");
        } else {
            log.info("✅ Admin account already exists");
        }
    }

    private void printStartupInfo() {
        log.info("============================================================");
        log.info("  ⚡ EventSphere — Started Successfully!");
        log.info("------------------------------------------------------------");
        log.info("  \ud83d\udd11 ADMIN Login   → admin@veltech.edu.in / Admin@123");
        log.info("  \ud83d\udc68‍\ud83c\udf93 STUDENT      → Self-register, instant access");
        log.info("  \ud83d\udc69‍\ud83c\udfeb FACULTY      → Self-register, needs admin approval");
        log.info("  \ud83c\udf10 Frontend      → http://localhost:5173");
        log.info("  \ud83d\udd27 Backend API   → http://localhost:8080");
        log.info("============================================================");
    }

    @java.lang.SuppressWarnings("all")
    
    public DataInitializer(final UserRepository userRepository, final PasswordEncoder passwordEncoder) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
    }
}
