// Generated by delombok at Thu Apr 23 17:18:39 IST 2026
package com.eventbooking.dto;

public class AnnouncementRequest {
    private String subject;
    private String message;
    private String targetDepartment; // null = all
    private Integer targetYear; // null = all

    @java.lang.SuppressWarnings("all")
    
    public AnnouncementRequest() {
    }

    @java.lang.SuppressWarnings("all")
    
    public String getSubject() {
        return this.subject;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getTargetDepartment() {
        return this.targetDepartment;
    }

    @java.lang.SuppressWarnings("all")
    
    public Integer getTargetYear() {
        return this.targetYear;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setSubject(final String subject) {
        this.subject = subject;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setTargetDepartment(final String targetDepartment) {
        this.targetDepartment = targetDepartment;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setTargetYear(final Integer targetYear) {
        this.targetYear = targetYear;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AnnouncementRequest)) return false;
        final AnnouncementRequest other = (AnnouncementRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$targetYear = this.getTargetYear();
        final java.lang.Object other$targetYear = other.getTargetYear();
        if (this$targetYear == null ? other$targetYear != null : !this$targetYear.equals(other$targetYear)) return false;
        final java.lang.Object this$subject = this.getSubject();
        final java.lang.Object other$subject = other.getSubject();
        if (this$subject == null ? other$subject != null : !this$subject.equals(other$subject)) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        final java.lang.Object this$targetDepartment = this.getTargetDepartment();
        final java.lang.Object other$targetDepartment = other.getTargetDepartment();
        if (this$targetDepartment == null ? other$targetDepartment != null : !this$targetDepartment.equals(other$targetDepartment)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AnnouncementRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $targetYear = this.getTargetYear();
        result = result * PRIME + ($targetYear == null ? 43 : $targetYear.hashCode());
        final java.lang.Object $subject = this.getSubject();
        result = result * PRIME + ($subject == null ? 43 : $subject.hashCode());
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 43 : $message.hashCode());
        final java.lang.Object $targetDepartment = this.getTargetDepartment();
        result = result * PRIME + ($targetDepartment == null ? 43 : $targetDepartment.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "AnnouncementRequest(subject=" + this.getSubject() + ", message=" + this.getMessage() + ", targetDepartment=" + this.getTargetDepartment() + ", targetYear=" + this.getTargetYear() + ")";
    }
}
