// Generated by delombok at Thu Apr 23 17:18:39 IST 2026
package com.eventbooking.dto;

public class AuthResponse {
    private String token;
    private Long userId;
    private String name;
    private String email;
    private String role;
    private String department;
    private String message;
    private boolean pending; // true if faculty account awaiting approval


    @java.lang.SuppressWarnings("all")
    
    public static class AuthResponseBuilder {
        @java.lang.SuppressWarnings("all")
        
        private String token;
        @java.lang.SuppressWarnings("all")
        
        private Long userId;
        @java.lang.SuppressWarnings("all")
        
        private String name;
        @java.lang.SuppressWarnings("all")
        
        private String email;
        @java.lang.SuppressWarnings("all")
        
        private String role;
        @java.lang.SuppressWarnings("all")
        
        private String department;
        @java.lang.SuppressWarnings("all")
        
        private String message;
        @java.lang.SuppressWarnings("all")
        
        private boolean pending;

        @java.lang.SuppressWarnings("all")
        
        AuthResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public AuthResponse.AuthResponseBuilder token(final String token) {
            this.token = token;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public AuthResponse.AuthResponseBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public AuthResponse.AuthResponseBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public AuthResponse.AuthResponseBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public AuthResponse.AuthResponseBuilder role(final String role) {
            this.role = role;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public AuthResponse.AuthResponseBuilder department(final String department) {
            this.department = department;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public AuthResponse.AuthResponseBuilder message(final String message) {
            this.message = message;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public AuthResponse.AuthResponseBuilder pending(final boolean pending) {
            this.pending = pending;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public AuthResponse build() {
            return new AuthResponse(this.token, this.userId, this.name, this.email, this.role, this.department, this.message, this.pending);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "AuthResponse.AuthResponseBuilder(token=" + this.token + ", userId=" + this.userId + ", name=" + this.name + ", email=" + this.email + ", role=" + this.role + ", department=" + this.department + ", message=" + this.message + ", pending=" + this.pending + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static AuthResponse.AuthResponseBuilder builder() {
        return new AuthResponse.AuthResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public String getToken() {
        return this.token;
    }

    @java.lang.SuppressWarnings("all")
    
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getRole() {
        return this.role;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getDepartment() {
        return this.department;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    
    public boolean isPending() {
        return this.pending;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setToken(final String token) {
        this.token = token;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setRole(final String role) {
        this.role = role;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setDepartment(final String department) {
        this.department = department;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setPending(final boolean pending) {
        this.pending = pending;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AuthResponse)) return false;
        final AuthResponse other = (AuthResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isPending() != other.isPending()) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$token = this.getToken();
        final java.lang.Object other$token = other.getToken();
        if (this$token == null ? other$token != null : !this$token.equals(other$token)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$role = this.getRole();
        final java.lang.Object other$role = other.getRole();
        if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
        final java.lang.Object this$department = this.getDepartment();
        final java.lang.Object other$department = other.getDepartment();
        if (this$department == null ? other$department != null : !this$department.equals(other$department)) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AuthResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isPending() ? 79 : 97);
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $token = this.getToken();
        result = result * PRIME + ($token == null ? 43 : $token.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $role = this.getRole();
        result = result * PRIME + ($role == null ? 43 : $role.hashCode());
        final java.lang.Object $department = this.getDepartment();
        result = result * PRIME + ($department == null ? 43 : $department.hashCode());
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 43 : $message.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "AuthResponse(token=" + this.getToken() + ", userId=" + this.getUserId() + ", name=" + this.getName() + ", email=" + this.getEmail() + ", role=" + this.getRole() + ", department=" + this.getDepartment() + ", message=" + this.getMessage() + ", pending=" + this.isPending() + ")";
    }

    @java.lang.SuppressWarnings("all")
    
    public AuthResponse() {
    }

    @java.lang.SuppressWarnings("all")
    
    public AuthResponse(final String token, final Long userId, final String name, final String email, final String role, final String department, final String message, final boolean pending) {
        this.token = token;
        this.userId = userId;
        this.name = name;
        this.email = email;
        this.role = role;
        this.department = department;
        this.message = message;
        this.pending = pending;
    }
}
