// Generated by delombok at Thu Apr 23 17:18:39 IST 2026
package com.eventbooking.dto;

public class CampaignRequest {
    private String customMessage; // optional extra message from faculty

    @java.lang.SuppressWarnings("all")
    
    public CampaignRequest() {
    }

    @java.lang.SuppressWarnings("all")
    
    public String getCustomMessage() {
        return this.customMessage;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCustomMessage(final String customMessage) {
        this.customMessage = customMessage;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CampaignRequest)) return false;
        final CampaignRequest other = (CampaignRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$customMessage = this.getCustomMessage();
        final java.lang.Object other$customMessage = other.getCustomMessage();
        if (this$customMessage == null ? other$customMessage != null : !this$customMessage.equals(other$customMessage)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CampaignRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $customMessage = this.getCustomMessage();
        result = result * PRIME + ($customMessage == null ? 43 : $customMessage.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "CampaignRequest(customMessage=" + this.getCustomMessage() + ")";
    }
}
