// Generated by delombok at Thu Apr 23 17:18:39 IST 2026
package com.eventbooking.dto;

public class RegisterRequest {
    private String name;
    private String email;
    private String password;
    private String role;
    private String department;
    private Integer yearOfStudy;
    private String vtuNumber;
    private String ttsNumber;


    @java.lang.SuppressWarnings("all")
    
    public RegisterRequest() {
    }

    @java.lang.SuppressWarnings("all")
    
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getRole() {
        return this.role;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getDepartment() {
        return this.department;
    }

    @java.lang.SuppressWarnings("all")
    
    public Integer getYearOfStudy() {
        return this.yearOfStudy;
    }

    public void setYearOfStudy(final Integer yearOfStudy) {
        this.yearOfStudy = yearOfStudy;
    }

    @java.lang.SuppressWarnings("all")
    public String getVtuNumber() { return this.vtuNumber; }

    @java.lang.SuppressWarnings("all")
    public String getTtsNumber() { return this.ttsNumber; }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RegisterRequest)) return false;
        final RegisterRequest other = (RegisterRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$yearOfStudy = this.getYearOfStudy();
        final java.lang.Object other$yearOfStudy = other.getYearOfStudy();
        if (this$yearOfStudy == null ? other$yearOfStudy != null : !this$yearOfStudy.equals(other$yearOfStudy)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$password = this.getPassword();
        final java.lang.Object other$password = other.getPassword();
        if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
        final java.lang.Object this$role = this.getRole();
        final java.lang.Object other$role = other.getRole();
        if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
        final java.lang.Object this$department = this.getDepartment();
        final java.lang.Object other$department = other.getDepartment();
        if (this$department == null ? other$department != null : !this$department.equals(other$department)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RegisterRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $yearOfStudy = this.getYearOfStudy();
        result = result * PRIME + ($yearOfStudy == null ? 43 : $yearOfStudy.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $password = this.getPassword();
        result = result * PRIME + ($password == null ? 43 : $password.hashCode());
        final java.lang.Object $role = this.getRole();
        result = result * PRIME + ($role == null ? 43 : $role.hashCode());
        final java.lang.Object $department = this.getDepartment();
        result = result * PRIME + ($department == null ? 43 : $department.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "RegisterRequest(name=" + this.getName() + ", email=" + this.getEmail() + ", password=" + this.getPassword() + ", role=" + this.getRole() + ", department=" + this.getDepartment() + ", yearOfStudy=" + this.getYearOfStudy() + ")";
    }
}
