// Generated by delombok at Thu Apr 23 17:18:39 IST 2026
package com.eventbooking.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

@Entity
@Table(name = "users")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotBlank(message = "Name is required")
    private String name;
    @Email(message = "Invalid email format")
    @NotBlank(message = "Email is required")
    @Column(unique = true, nullable = false)
    private String email;
    @NotBlank(message = "Password is required")
    @com.fasterxml.jackson.annotation.JsonIgnore
    private String password;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role = Role.STUDENT;
    private String department;
    // Student year (1=1st year, 2=2nd year, 3=3rd year, 4=4th year)
    private Integer yearOfStudy;
    // STUDENT & ADMIN auto-approved; FACULTY needs admin approval
    @Column(nullable = false)
    private boolean approved = true;
    @Column(columnDefinition = "LONGTEXT")
    private String faceDescriptor;


    private String vtuNumber;
    private String ttsNumber;

    /** For external (non-VelTech) users */
    private String collegeName;
    private String collegeState;
    private String collegeLocation;

    public enum Role {
        ADMIN, FACULTY, STUDENT;
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() { return this.id; }
    @java.lang.SuppressWarnings("all")
    public String getName() { return this.name; }
    @java.lang.SuppressWarnings("all")
    public String getEmail() { return this.email; }
    @java.lang.SuppressWarnings("all")
    public String getPassword() { return this.password; }
    @java.lang.SuppressWarnings("all")
    public Role getRole() { return this.role; }
    @java.lang.SuppressWarnings("all")
    public String getDepartment() { return this.department; }
    @java.lang.SuppressWarnings("all")
    public Integer getYearOfStudy() { return this.yearOfStudy; }
    @java.lang.SuppressWarnings("all")
    public boolean isApproved() { return this.approved; }
    @java.lang.SuppressWarnings("all")
    public String getVtuNumber() { return this.vtuNumber; }
    @java.lang.SuppressWarnings("all")
    public String getTtsNumber() { return this.ttsNumber; }
    @java.lang.SuppressWarnings("all")
    public String getFaceDescriptor() { return this.faceDescriptor; }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) { this.id = id; }
    @java.lang.SuppressWarnings("all")
    public void setName(final String name) { this.name = name; }
    @java.lang.SuppressWarnings("all")
    public void setEmail(final String email) { this.email = email; }
    @java.lang.SuppressWarnings("all")
    public void setPassword(final String password) { this.password = password; }
    @java.lang.SuppressWarnings("all")
    public void setRole(final Role role) { this.role = role; }
    @java.lang.SuppressWarnings("all")
    public void setDepartment(final String department) { this.department = department; }
    @java.lang.SuppressWarnings("all")
    public void setYearOfStudy(final Integer yearOfStudy) { this.yearOfStudy = yearOfStudy; }
    @java.lang.SuppressWarnings("all")
    public void setApproved(final boolean approved) { this.approved = approved; }
    @java.lang.SuppressWarnings("all")
    public void setVtuNumber(final String vtuNumber) { this.vtuNumber = vtuNumber; }
    public void setTtsNumber(final String ttsNumber) { this.ttsNumber = ttsNumber; }
    public void setFaceDescriptor(final String faceDescriptor) { this.faceDescriptor = faceDescriptor; }

    public String getCollegeName() { return collegeName; }
    public void setCollegeName(String collegeName) { this.collegeName = collegeName; }
    public String getCollegeState() { return collegeState; }
    public void setCollegeState(String collegeState) { this.collegeState = collegeState; }
    public String getCollegeLocation() { return collegeLocation; }
    public void setCollegeLocation(String collegeLocation) { this.collegeLocation = collegeLocation; }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof User)) return false;
        final User other = (User) o;
        if (this.getId() == null ? other.getId() != null : !this.getId().equals(other.getId())) return false;
        return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        return this.getId() == null ? 43 : this.getId().hashCode();
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "User(id=" + this.getId() + ", email=" + this.getEmail() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public User() {
    }

    @java.lang.SuppressWarnings("all")
    public User(final Long id, final String name, final String email, final String password, final Role role, final String department, final Integer yearOfStudy, final boolean approved, final String vtuNumber, final String ttsNumber) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.role = role;
        this.department = department;
        this.yearOfStudy = yearOfStudy;
        this.approved = approved;
        this.vtuNumber = vtuNumber;
        this.ttsNumber = ttsNumber;
    }
}
