// Generated by delombok at Thu Apr 23 17:18:39 IST 2026
package com.eventbooking.service;

import com.eventbooking.model.Booking;
import com.eventbooking.model.Event;
import com.eventbooking.model.Event.EventStatus;
import com.eventbooking.model.User;
import com.eventbooking.repository.BookingRepository;
import com.eventbooking.repository.EventRepository;
import com.eventbooking.repository.UserRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;
import java.util.Map;

@Service
public class EventService {
    @java.lang.SuppressWarnings("all")
    
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(EventService.class);
    private final EventRepository eventRepository;
    private final BookingRepository bookingRepository;
    private final UserRepository userRepository;
    private final EmailService emailService;
    private final NotificationService notificationService;

    public User getUserByEmail(String email) {
        return userRepository.findByEmail(email).orElseThrow(() -> new RuntimeException("User not found: " + email));
    }

    // ── Create Event (saves as DRAFT unless explicitly set) ──────────
    @Transactional
    public Event createEvent(Event event, String creatorEmail) {
        if (event.getAvailableTickets() == null) {
            event.setAvailableTickets(event.getTotalTickets());
        }
        // Default to DRAFT if not specified
        if (event.getStatus() == null) {
            event.setStatus(EventStatus.DRAFT);
        }
        User creator = getUserByEmail(creatorEmail);
        event.setCreatedBy(creator);
        
        Event saved = eventRepository.save(event);
        log.info("Event saved [{}] status={}", saved.getEventName(), saved.getStatus());
        // Only notify users when event is published
        if (saved.getStatus() == EventStatus.PUBLISHED || saved.getStatus() == EventStatus.REGISTRATION_OPEN) {
            notifyEligibleUsers(saved);
        }
        return saved;
    }

    // ── Update Event ──────────────────────────────────────────────────
    @Transactional
    public Event updateEvent(Long id, Event updated) {
        Event existing = eventRepository.findById(id).orElseThrow(() -> new RuntimeException("Event not found: " + id));
        EventStatus oldStatus = existing.getStatus();
        existing.setEventName(updated.getEventName());
        existing.setDepartment(updated.getDepartment());
        existing.setOrganizingDepartments(updated.getOrganizingDepartments());
        existing.setStartDate(updated.getStartDate());
        existing.setEndDate(updated.getEndDate());
        existing.setTime(updated.getTime());
        existing.setVenue(updated.getVenue());
        existing.setPrice(updated.getPrice());
        existing.setDescription(updated.getDescription());
        existing.setShortDescription(updated.getShortDescription());
        existing.setFullDescription(updated.getFullDescription());
        existing.setImageUrl(updated.getImageUrl());
        existing.setTargetDepartments(updated.getTargetDepartments());
        existing.setTargetYears(updated.getTargetYears());
        existing.setNumberOfDays(updated.getNumberOfDays());
        existing.setAccommodationProvided(updated.getAccommodationProvided());
        existing.setAccommodationAvailable(updated.getAccommodationAvailable());
        existing.setCustomRegistrationFields(updated.getCustomRegistrationFields());
        existing.setRegistrationStartDate(updated.getRegistrationStartDate());
        existing.setRegistrationEndDate(updated.getRegistrationEndDate());
        // New fields
        if (updated.getEventType() != null) existing.setEventType(updated.getEventType());
        if (updated.getLocationType() != null) existing.setLocationType(updated.getLocationType());
        if (updated.getStartDateTime() != null) existing.setStartDateTime(updated.getStartDateTime());
        if (updated.getEndDateTime() != null) existing.setEndDateTime(updated.getEndDateTime());
        if (updated.getMaxParticipants() != null) existing.setMaxParticipants(updated.getMaxParticipants());
        if (updated.getIsTeamEvent() != null) existing.setIsTeamEvent(updated.getIsTeamEvent());
        if (updated.getMaxTeamSize() != null) existing.setMaxTeamSize(updated.getMaxTeamSize());
        
        if (updated.getExpenses() != null) {
            existing.getExpenses().clear();
            existing.getExpenses().addAll(updated.getExpenses());
        }
        if (updated.getReportPhotos() != null) {
            existing.getReportPhotos().clear();
            existing.getReportPhotos().addAll(updated.getReportPhotos());
        }

        // Handle status transitions
        if (updated.getStatus() != null) {
            existing.setStatus(updated.getStatus());
        }
        // Update ticket counts
        if (updated.getTotalTickets() != null) {
            int diff = updated.getTotalTickets() - existing.getTotalTickets();
            existing.setTotalTickets(updated.getTotalTickets());
            existing.setAvailableTickets(Math.max(0, existing.getAvailableTickets() + diff));
        }
        Event saved = eventRepository.save(existing);
        // Send notification email when transitioning to PUBLISHED
        if (oldStatus == EventStatus.DRAFT && saved.getStatus() == EventStatus.PUBLISHED) {
            notifyEligibleUsers(saved);
            log.info("Event published — notifications sent for \'{}\'", saved.getEventName());
        }
        // Send notification when registration opens
        if (oldStatus != EventStatus.REGISTRATION_OPEN && saved.getStatus() == EventStatus.REGISTRATION_OPEN) {
            notifyEligibleUsers(saved);
            log.info("Registration opened — notifications sent for \'{}\'", saved.getEventName());
        }
        return saved;
    }

    // ── Lifecycle Transitions ─────────────────────────────────────────
    @Transactional
    public Event publishEvent(Long id) {
        return changeStatus(id, EventStatus.PUBLISHED, true);
    }

    @Transactional
    public Event openRegistration(Long id) {
        return changeStatus(id, EventStatus.REGISTRATION_OPEN, true);
    }

    @Transactional
    public Event pauseRegistration(Long id) {
        return changeStatus(id, EventStatus.REGISTRATION_PAUSED, false);
    }

    @Transactional
    public Event closeRegistration(Long id) {
        return changeStatus(id, EventStatus.REGISTRATION_CLOSED, false);
    }

    @Transactional
    public Event postponeEvent(Long id) {
        return changeStatus(id, EventStatus.POSTPONED, false);
    }

    @Transactional
    public Event completeEvent(Long id) {
        return changeStatus(id, EventStatus.COMPLETED, false);
    }

    private Event changeStatus(Long id, EventStatus newStatus, boolean notifyUsers) {
        Event event = eventRepository.findById(id).orElseThrow(() -> new RuntimeException("Event not found: " + id));
        EventStatus old = event.getStatus();
        event.setStatus(newStatus);
        Event saved = eventRepository.save(event);
        log.info("Event '{}' status: {} → {}", event.getEventName(), old, newStatus);
        if (notifyUsers) {
            try {
                notifyEligibleUsers(saved);
            } catch (Exception e) {
                log.error("Failed to send notifications for event '{}': {}", saved.getEventName(), e.getMessage());
                // Do NOT rethrow — status change succeeded, email failure should not roll back
            }
        }
        return saved;
    }

    @Transactional
    public Event addCoordinator(Long id, Long userId) {
        Event event = eventRepository.findById(id).orElseThrow(() -> new RuntimeException("Event not found: " + id));
        User user = userRepository.findById(userId).orElseThrow(() -> new RuntimeException("User not found: " + userId));
        event.getCoordinators().add(user);
        return eventRepository.save(event);
    }

    @Transactional
    public Event removeCoordinator(Long id, Long userId) {
        Event event = eventRepository.findById(id).orElseThrow(() -> new RuntimeException("Event not found: " + id));
        event.getCoordinators().removeIf(u -> u.getId().equals(userId));
        return eventRepository.save(event);
    }

    // ── Cancel Event ──────────────────────────────────────────────────
    @Transactional
    public Map<String, Object> cancelEvent(Long id) {
        Event event = eventRepository.findById(id).orElseThrow(() -> new RuntimeException("Event not found: " + id));
        event.setStatus(EventStatus.CANCELLED);
        eventRepository.save(event);
        List<Booking> bookings = bookingRepository.findByEventId(id);
        bookings.forEach(b -> b.setStatus(Booking.BookingStatus.CANCELLED));
        bookingRepository.saveAll(bookings);
        if (!bookings.isEmpty()) {
            emailService.sendEventCancellationEmails(event, bookings);
        }
        log.info("Event \'{}\' cancelled. {} bookings cancelled.", event.getEventName(), bookings.size());
        return Map.of("message", "Event cancelled successfully.", "eventName", event.getEventName(), "affectedBookings", bookings.size());
    }

    // ── Campaign ──────────────────────────────────────────────────────
    public Map<String, Object> sendCampaign(Long id, String customMessage, org.springframework.web.multipart.MultipartFile file) {
        Event event = eventRepository.findById(id).orElseThrow(() -> new RuntimeException("Event not found: " + id));
        if (event.getStatus() == EventStatus.CANCELLED) {
            throw new RuntimeException("Cannot send campaign for a cancelled event.");
        }
        byte[] fileBytes = null;
        String fileName = null;
        if (file != null && !file.isEmpty()) {
            try {
                fileBytes = file.getBytes();
                fileName = file.getOriginalFilename();
            } catch (Exception e) {
                throw new RuntimeException("Failed to read attached file: " + e.getMessage());
            }
        }
        List<User> eligible = getEligibleUsers(event);
        emailService.sendCampaignEmails(event, eligible, customMessage, fileBytes, fileName);
        log.info("Campaign triggered for \'{}\' → {} recipients", event.getEventName(), eligible.size());
        return Map.of("message", "Campaign emails queued successfully!", "eventName", event.getEventName(), "recipientCount", eligible.size());
    }

    // ── Helpers ───────────────────────────────────────────────────────
    private void notifyEligibleUsers(Event event) {
        List<User> eligible = getEligibleUsers(event);
        if (!eligible.isEmpty()) {
            emailService.sendNewEventNotifications(event, eligible);
            log.info("Queued notifications for {} users for \'{}\'", eligible.size(), event.getEventName());
        }
    }

    public List<User> getEligibleUsers(Event event) {
        List<User> faculty = new java.util.ArrayList<>(userRepository.findByRoleAndApproved(User.Role.FACULTY, true));
        List<User> students = new java.util.ArrayList<>(userRepository.findByRoleAndApproved(User.Role.STUDENT, true));

        java.util.Set<String> depts = event.getTargetDepartments();
        java.util.Set<Integer> years = event.getTargetYears();

        if (depts != null && !depts.isEmpty()) {
            students.removeIf(s -> s.getDepartment() == null || !depts.contains(s.getDepartment()));
        }
        if (years != null && !years.isEmpty()) {
            students.removeIf(s -> s.getYearOfStudy() == null || !years.contains(s.getYearOfStudy()));
        }

        faculty.addAll(students);

        // Also add all attendees already registered for this event!
        List<Booking> bookings = bookingRepository.findByEventId(event.getId());
        for (Booking b : bookings) {
            if (b.getAttendees() != null) {
                for (com.eventbooking.model.Attendee a : b.getAttendees()) {
                    if (a.getEmail() != null && !a.getEmail().isBlank()) {
                        User dummy = new User();
                        dummy.setName(a.getName() != null ? a.getName() : "Student");
                        dummy.setEmail(a.getEmail());
                        dummy.setRole(User.Role.STUDENT);
                        faculty.add(dummy);
                    }
                }
            }
        }

        // Deduplicate by email
        List<User> unique = new java.util.ArrayList<>();
        java.util.Set<String> seenEmails = new java.util.HashSet<>();
        for (User u : faculty) {
            if (u.getEmail() != null && seenEmails.add(u.getEmail())) {
                unique.add(u);
            }
        }
        
        return unique;
    }

    // ── Approval Workflow ─────────────────────────────────────────────

    /** Faculty submits event for admin approval */
    @Transactional
    public Event submitForApproval(Long id) {
        Event event = eventRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Event not found: " + id));
        if (event.getStatus() != EventStatus.DRAFT) {
            throw new RuntimeException("Only DRAFT events can be submitted for approval.");
        }
        event.setStatus(EventStatus.PENDING_APPROVAL);
        Event saved = eventRepository.save(event);
        log.info("Event '{}' submitted for approval.", saved.getEventName());
        return saved;
    }

    /** Admin approves event */
    @Transactional
    public Event approveEvent(Long id) {
        Event event = eventRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Event not found: " + id));
        if (event.getStatus() != EventStatus.PENDING_APPROVAL) {
            throw new RuntimeException("Event is not pending approval.");
        }
        event.setStatus(EventStatus.APPROVED);
        Event saved = eventRepository.save(event);
        log.info("Event '{}' approved.", saved.getEventName());
        // Notify creator
        try {
            if (saved.getCreatedBy() != null) {
                notificationService.notifyEventApproved(saved.getCreatedBy().getId(), saved.getEventName());
            }
        } catch (Exception e) {
            log.error("Approval notification failed: {}", e.getMessage());
        }
        return saved;
    }

    /** Admin rejects event with reason */
    @Transactional
    public Event rejectEvent(Long id, String reason) {
        Event event = eventRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Event not found: " + id));
        if (event.getStatus() != EventStatus.PENDING_APPROVAL) {
            throw new RuntimeException("Event is not pending approval.");
        }
        event.setStatus(EventStatus.REJECTED);
        Event saved = eventRepository.save(event);
        log.info("Event '{}' rejected. Reason: {}", saved.getEventName(), reason);
        // Notify creator
        try {
            if (saved.getCreatedBy() != null) {
                notificationService.notifyEventRejected(
                        saved.getCreatedBy().getId(), saved.getEventName(), reason);
            }
        } catch (Exception e) {
            log.error("Rejection notification failed: {}", e.getMessage());
        }
        return saved;
    }

    // ── Constructor ───────────────────────────────────────────────────
    public EventService(final EventRepository eventRepository,
                        final BookingRepository bookingRepository,
                        final UserRepository userRepository,
                        final EmailService emailService,
                        final NotificationService notificationService) {
        this.eventRepository = eventRepository;
        this.bookingRepository = bookingRepository;
        this.userRepository = userRepository;
        this.emailService = emailService;
        this.notificationService = notificationService;
    }
}
